services:
  mongo-crypto-db:
    image: 'mongo:latest'
    container_name: 'mongo-crypto-db'
    ports:
      - '27017:27017'
    volumes:
      - crypto-db-volume:/data/db

  cbt-mongo-seed:
    image: 'cbt-mongo-seed'
    container_name: 'cbt-mongo-seed'
    depends_on:
      - mongo-crypto-db

  crypto-balance-tracker-login:
    build:
      context: ../crypto-balance-tracker-login
      dockerfile: Dockerfile
    container_name: 'crypto-balance-tracker-login'
    depends_on:
      - mongo-crypto-db
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - ENV_PROFILE=docker
    ports:
      - '8081:8081'

  crypto-balance-tracker-kt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'crypto-balance-tracker-kt'
    depends_on:
      - mongo-crypto-db
      - crypto-balance-tracker-login
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - DEMO_COINGECKO_API_KEY=${DEMO_COINGECKO_API_KEY}
      - PRO_COINGECKO_API_KEY=${PRO_COINGECKO_API_KEY}
      - ENV_PROFILE=docker
    ports:
      - '8080:8080'

  crypto-balance-tracker-ui:
    build:
      context: ../crypto-balance-tracker-ui
      dockerfile: Dockerfile
    container_name: 'crypto-balance-tracker-ui'
    depends_on:
      - crypto-balance-tracker-kt
    ports:
      - '5173:5173'

volumes:
  crypto-db-volume:
