version: '3.9'

services:
  mongo-crypto-db:
    image: 'mongo:latest'
    container_name: 'mongo-crypto-db'
    ports:
      - '27017:27017'
    volumes:
      - crypto-db-volume:/data/db

  crypto-balance-tracker-kt:
    image: 'crypto-balance-tracker-kt:latest'
    container_name: 'crypto-balance-tracker-kt'
    depends_on:
      - mongo-crypto-db
    environment:
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}
      - DEMO_COINGECKO_API_KEY=${DEMO_COINGECKO_API_KEY}
      - PRO_COINGECKO_API_KEY=${PRO_COINGECKO_API_KEY}
      - ENV_PROFILE=docker
    ports:
      - '8080:8080'

  crypto-balance-tracker-ui:
    image: 'crypto-balance-tracker-ui:latest'
    container_name: 'crypto-balance-tracker-ui'
    depends_on:
      - crypto-balance-tracker-kt
    ports:
      - '5173:5173'

volumes:
  crypto-db-volume: