spring:
  application:
    name: crypto-balance-tracker-kt
  profiles:
    active: ${ENV_PROFILE:local}
    group:
      default: local

coingecko:
  api-key:
    demo: ${DEMO_COINGECKO_API_KEY}
    pro: ${PRO_COINGECKO_API_KEY}
  url:
    free: "https://api.coingecko.com/api/v3"
    pro: "https://pro-api.coingecko.com/api/v3"

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1

crypto:
  insights:
    max-single-items-count: 15
    elements-page: 10
  scheduler:
    update:
      quantity: 10
      cron: "0 */5 * ? * *"

day-balance:
  cron: "0 */30 * ? * *"

security:
  enabled: false

jwt:
  signing-key: ${JWT_SIGNING_KEY}

allowed-origins: "http://localhost:5173"
