spring:
  application:
    name: crypto-balance-tracker-kt
  profiles:
    active: ${ENV_PROFILE:local}
    group:
      default: local

coingecko:
  api-key:
    demo: ${DEMO_COINGECKO_API_KEY}
    pro: ${PRO_COINGECKO_API_KEY}
  url:
    free: "https://api.coingecko.com/api/v3"
    pro: "https://pro-api.coingecko.com/api/v3"

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1

logging:
  charset:
    console: UTF-8
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %cyan([ %thread ]) %green(%logger) - %boldCyan(%msg%n)"

max-limit-crypto: 10

security:
  enabled: false

jwt:
  signing-key: ${JWT_SIGNING_KEY}

allowed-origins: "http://localhost:5173"