server:
  port: 8080

spring:
  data:
    mongodb:
      database: crypto_db # TODO
      auto-index-creation: true
      host: mongo-crypto-db
      port: 27017

coingecko:
  api-key: ${COINGECKO_API_KEY}
  url: "https://api.coingecko.com/api/v3"
  pro:
    url: "https://pro-api.coingecko.com/api/v3"

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1

logging:
  charset:
    console: UTF-8
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) %cyan([ %thread ]) %green(%logger) - %boldCyan(%msg%n)"

max-limit-crypto: 9

security:
  enabled: false

jwt:
  signing-key: ${JWT_SIGNING_KEY}

allowed-origins: "http://localhost:5173"