name: Build, Test & Publish

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  call-build-test-and-publish:
    uses: lucasdistasi/ci-workflows/.github/workflows/build-test-and-publish.yml@main
