name: main.yml

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  call-build-test-and-publish:
    uses: lucasdistasi/ci-workflows/.github/workflows/build-test-and-publish.yml@main
    secrets:
      actions-token: ${{ secrets.ACTIONS_TOKEN }}
